baseURL = "https://example.com/portfolio_k"
languageCode = "en-us"
title = "Some Title"
theme = "hugo-theme-anubis-main"

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  post = "/:filename/"

[params]
  description = "Some description"
  contentBackgroundColor = "#fff"
  contentTextColor = "#212529"
  contentLinkColor = "#007bff"
  contentLinkHoverColor = "#0056b3"
  navbarBackgroundColor = "#212529"
  navbarLinkColor = "rgba(255, 255, 255, 0.75)"
  navbarLinkHoverColor = "rgba(255, 255, 255, 1)"
  wrapperMaxWidth = "800px"
  customDateFormat = "Jan 2, 2006"
  customCodeStyle = true
  customBlockquoteStyle = true
  showPostSummary = false
  googleAnalytics = "UA-123456789-1"
  cookieConsent = true
  includeBootstrapJs = false
  faviconSafariPinnedTabColor = "#5bbad5"
  faviconMsApplicationTileColor = "#da532c"
  faviconThemeColor = "#ffffff"

[menu]
  [[menu.nav]]
  name = "Home"
  url = "/home/"
  weight = 1
  [[menu.nav]]
  name = "Posts"
  url = "/"
  weight = 2
  [[menu.nav]]
  name = "About"
  url = "/about/"
  weight = 3  
  [[menu.nav]]
  name = "1"
  url = "/1/"
  weight = 4
  [[menu.nav]]
  name = "2"
  url = "/2/"
  weight = 5
  [[menu.nav]]
  name = "3"
  url = "/3/"
  weight = 6
  [[menu.nav]]
  name = "4"
  url = "/4/"
  weight = 7
  [[menu.nav]]
  name = "Практики"
  url = "/practices/"
  weight = 8
  [[menu.nav]]
  name = "Курсовые работы"
  url = "/kurs/"
  weight = 9

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 2
