baseURL = "https://example.com/portfolio_k"
languageCode = "en-us"
title = "Some Title"
theme = "hugo-theme-anubis-main"

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  post = "/:filename/"

[params]
  author = "Данил"
  description = "Мое новое портфолио, созданное на Hugo с темой Anubis."
  email = "Ваш_email@example.com" # Используется для микроформатов
  avatar = "/images/avatar.jpg" # Добавьте свое фото в static/images/
  
  dateFormat = "2006-01-02"
  style = "auto" # Автоматический светлый/темный режим
  mainSections = [ "posts" ] # На главной странице будут отображаться посты
  toc = true # Включить оглавление
  copyCodeButton = true
  rssAsSocialIcon = true # Добавить иконку RSS в соц.сети
  
  # Настройки социальных сетей
[[params.social]]
  id = "github"
  name = "danyakr" # Это сгенерирует ссылку на ваш профиль GitHub
[[params.social]]
  id = "telegram"
  name = "ВашТелеграм" # Пример

[menu]
  [[menu.main]]
  name = "Главная"
  url = "/"
  weight = 1
  [[menu.main]]
  name = "Архив"
  url = "/posts/" # Ссылка на все посты
  weight = 2
  [[menu.main]]
  name = "Обо мне"
  url = "/about/" # Убедитесь, что у вас есть файл content/about.md
  weight = 3
  
# [menu]  
#   [[menu.nav]]
#   name = "Home"
#   url = "/home/"
#   weight = 1
#   [[menu.nav]]
#   name = "Posts"
#   url = "/"
#   weight = 2
#   [[menu.nav]]
#   name = "About"
#   url = "/about/"
#   weight = 3  
#   [[menu.nav]]
#   name = "1"
#   url = "/1/"
#   weight = 4
#   [[menu.nav]]
#   name = "2"
#   url = "/2/"
#   weight = 5
#   [[menu.nav]]
#   name = "3"
#   url = "/3/"
#   weight = 6
#   [[menu.nav]]
#   name = "4"
#   url = "/4/"
#   weight = 7
#   [[menu.nav]]
#   name = "Практики"
#   url = "/practices/"
#   weight = 8
#   [[menu.nav]]
#   name = "Курсовые работы"
#   url = "/kurs/"
#   weight = 9

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 2
