baseURL = "https://danyakr.github.io/portfolio_k/" # ВНИМАНИЕ! Исправленный адрес для GitHub Pages
languageCode = "ru-ru" # Русский язык
title = "Портфолио Данила"
theme = "hugo-theme-anubis-main" # Убедитесь, что это имя папки
paginate = 10 # Отображение 10 элементов на странице

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  post = "/:filename/"

[params]
  author = "Данил" # Ваше имя
  description = "Мое портфолио на Hugo с темой Anubis."
  email = "Ваш_email@example.org" # ВНИМАНИЕ! Замените на свой email
  avatar = "/images/avatar.jpg" # Добавьте свое фото в static/images/
  
  # Параметры из Anubis
  dateFormat = "2006-01-02"
  paginationSinglePost = true
  style = "auto" # Автоматический темный/светлый режим с переключателем
  readMore = false
  readNextPosts = 5 # Показывать 5 похожих постов
  copyCodeButton = true
  rssAsSocialIcon = true
  mathjax = false
  
  # Установите ваши основные разделы контента
  mainSections = [ "1", "2", "3", "4", "kurs", "practices" ] 

# --- Секция социальных сетей (ОБЯЗАТЕЛЬНО: ДВОЙНЫЕ СКОБКИ, ОТДЕЛЬНО ОТ [params]) ---

[[params.social]]
  id = "github"
  name = "danyakr" 

[[params.social]]
  id = "telegram"
  name = "ВашТелеграм" # ВНИМАНИЕ! Замените на ваш логин Telegram

# --- Настройки меню (ОБЯЗАТЕЛЬНО: [[menu.main]]) ---

[menu]
  [[menu.main]]
  name = "Главная"
  url = "/"
  weight = 1
  
  [[menu.main]]
  name = "Архив"
  url = "/posts/" 
  weight = 2
  
  [[menu.main]]
  name = "Обо мне"
  url = "/about/" 
  weight = 3

  [[menu.main]]
  name = "Курсовые работы"
  url = "/kurs/" 
  weight = 4
  
  [[menu.main]]
  name = "Практики"
  url = "/practices/" 
  weight = 5

# --- Настройки Markdown/HTML ---

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true # Разрешение HTML/стилей Anubis
      xHTML = false
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 2
